### ISSUE TITLE
feature request - add date and time to the transaction

### ISSUE THREAD

**Issue by avihai-developer** [nano-wallet-company/nano-wallet-android#12]
Right now i can't see when i sent or recive transactions without open the block explorer for each transaction

**Comment by berlangerc** [comment]
This would be a usefull feature, this issue is that the timestamp is not availble in the block.

What if we capture the local timestamp and store it on the mobile phone when doing a transaction?
What if it's an incoming transaction? Can we save the timestamp on that event?
What if the user creates a new wallet, how do we get the timestamps of all the transactions for that wallet?
Can we use a third party service (Nanode) to get (some) timestamps?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
