### ISSUE TITLE
Use SecurityRandom.getInstanceStrong

### ISSUE THREAD

**Issue by rotilho** [nano-wallet-company/nano-wallet-android#2]
Hello!

The recommendation is to use getInstanceStrong (instead of new SecurityRandom) for creation of private keys / seeds etc which ensure RNG algorithm is strong https://developer.android.com/reference/java/security/SecureRandom.html#getInstanceStrong()

You can also generate the seed in better fashion way using nextBytes like in https://github.com/rotilho/jnano-commons/blob/master/src/main/java/com/rotilho/jnano/commons/NanoSeeds.java#L24

Btw, I worked in a commons library which could remove several lines of code here. You can find more in https://github.com/rotilho/jnano-commons

**Comment by MarcIlunga** [comment]
Hi,

I think this is a separate issue but it is a bit related.
The code makes use of Java Strings to store sensitive data such as the seed and the private keys..

This is generally considered bad practice given that Strings can live longer than needed in Memory and it is also affects performance because there's always a String to byte[] conversion than can be avoid.

Is there any reason the team decided to do it that way?

Regards

**Comment by PlasmaPower** [comment]
We use LinuxSecureRandom to source randomness from `/dev/urandom` @rotilho 
https://github.com/nano-wallet-company/nano-wallet-android/blob/191c0f32587d0f5eb49b05873555db6172de2fdf/app/src/main/java/co/nano/nanowallet/util/LinuxSecureRandom.java

@MarcIlunga that won't matter unless an attacker has root, in which case they could just take the seed out of the filesystem anyway. Performance also doesn't matter for that case. It's insignificant compared to the latency of network operations.

**Comment by MarcIlunga** [comment]
@PlasmaPower  Thanks for you answer! I know the issue is closed but I, however disagree with what you said. Indeed a rooted device is the worse that can happen but loooking at your code I observed the following: The seed is stored encrypted on the filestystem using AndroidVault meaning that an attacker still needs find the encryption password to retrieve the seed. Fortunately for him you used AndroidVault with a preshared secret Key that is hardcoded in the source code and given that the seed(the other seed to derive the encryption key) is in plaintext then, they can derive the password to the vault and get the encryption key and get the seed. 

My point is I am puzzled by why you hint at providing good security for the app(Using Vaults, encryption and so on..) but do not use them fully. 

For example AndroidVault can be used with a in Memory only encryption key derived for a password using a PKDF. This is is another opportunity to perform some root detection and avoid loading any sensitive data in memory as long the phone is rooted. Also byte[] can be easily zerod-out or filled with garbage living the for only a short amount of time exposed.

Obviously depending on the skills and creativity of the attacker they can still try to go around that, but that task becomes more difficult.

Given the sensitivity  of the data(potentially a lot of Money), I think there is a case to be made for a greater security.  I would expect my crypot wallet to be at least as secure as my banking app(which is another topic ;) ).

All the best,

Marc

**Comment by rotilho** [comment]
@PlasmaPower are there any specific reason to choose `/dev/urandom` instead of `SecureRandom getInstanceStrong`? The SHA1PRNG should be as fast as urandom and don't require any special code

**Comment by PlasmaPower** [comment]
I'm not sure. Because it's provided by Linux, it's definitely going to be available on all versions and secure on all versions though.
