### ISSUE TITLE
Interested in introducing kotlin into the project

### ISSUE THREAD

**Issue by athkalia** [nano-wallet-company/nano-wallet-android#23]
Hello,

Kotlin https://developer.android.com/kotlin/ is the new trend in Android, officially supported by Google. Are you interested in adding support for it in the project? (not talking about actually migrating the project to Kotlin, that does not need to happen. Kotlin and Java can co-exist)

Cheers

**Comment by PlasmaPower** [comment]
I'm not sure that's a good idea, since a lot more people know Java than Kotlin, including on our team.

**Comment by zackshapiro** [comment]
Agreed. There’s no need to change the language this is in. Let’s just build
features and fix bug. Thanks!

Best,
Zack


On Jun 30, 2018 at 6:16 AM, Lee Bousfield <notifications@github.com> wrote:


I'm not sure that's a good idea, since a lot more people know Java than
Kotlin, including on our team.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-android/issues/23#issuecomment-401531766>,
or mute the thread

**Comment by slanos** [comment]
My wallet, Pocket Nano, was written in Kotlin (almost) completely. I will be open sourcing the application once I add all of the features that I plan on implementing. If you are interested in joining the project, let me know and we can discuss!!

**Comment by athkalia** [comment]
Sure thing. I'll think come up with other ways to contribute :)

Cheers,
Sakis
