### ISSUE TITLE
Seed does not match. Please try again. (when update from 1.0.0 to 1.0.2)

### ISSUE THREAD

**Issue by rodrigoslayertech** [nano-wallet-company/nano-wallet-android#8]
"Please verify your new Wallet Seed by typing it in below:"
* i put my new generated seed*
BUT: "Seed does not match. Please try again."

I tried with lowercase, uppercase characters and without spaces.
Is this a bug?
I can not verify my seed.

**Comment by zackshapiro** [comment]
64 characters?


On Jun 22, 2018 at 2:29 PM, Rodrigo Vieira <notifications@github.com> wrote:


"Please verify your new Wallet Seed by typing it in below:"

   - i put my new generated seed*
   BUT: "Seed does not match. Please try again."

I tried with lowercase, uppercase characters and without spaces.
Is this a bug?
I can not verify my seed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-android/issues/8>, or mute
the thread

**Comment by rodrigoslayertech** [comment]
Yes. The seed with 64 characters. Should I put the old seed instead of the new seed?

**Comment by zackshapiro** [comment]
No. Try putting the new seed in a wallet like Nanovault.io and see if it
loads okay



On Jun 22, 2018 at 3:18 PM, Rodrigo Vieira <notifications@github.com> wrote:


Yes. The seed with 64 characters. Should I put the old seed instead of the
new seed?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-android/issues/8#issuecomment-399553568>,
or mute the thread

**Comment by rodrigoslayertech** [comment]
I generated a new seed from 1.0.2 version, why do I have to put a seed from another wallet?

**Comment by zackshapiro** [comment]
You shouldn’t have to I’m just trying to debug without seeing your phone or
seed (don’t share it). Make sure it’s 64 Chars, no spaces. If it works in a
different wallet it might be a bug detecting the valid seed in the android
wallet. If the other wallet doesn’t work, it’s user error. That’s what I’m
trying to get at


On Jun 22, 2018 at 3:32 PM, Rodrigo Vieira <notifications@github.com> wrote:


I generated a new seed from 1.0.2 version, why do I have to put a seed from
another wallet?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-android/issues/8#issuecomment-399558114>,
or mute the thread

**Comment by rodrigoslayertech** [comment]
I understand now.
I have tested in NanoVault and my new generated seed from version 1.0.2 works!
But like I said, in seed check it does not work when update from 1.0.0 to 1.0.2!

**Comment by zackshapiro** [comment]
What if you log out of the android wallet and log back in with the new seed?

**Comment by rodrigoslayertech** [comment]
Also works! I think the bug is only on the seed check screen in the Update of the New Seed Wizard.

**Comment by zackshapiro** [comment]
Will look into. Thanks

Best,
Zack


On Jun 22, 2018 at 4:16 PM, Rodrigo Vieira <notifications@github.com> wrote:


Also works! I think the bug is only on the seed check screen in the update
wizard.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-android/issues/8#issuecomment-399569602>,
or mute the thread

**Comment by zackshapiro** [comment]
@overhound @dungtienta Would one of you mind looking into in what case the 64 char seed entry here might fail?

**Comment by dungtienta** [comment]
@zackshapiro I can sometime tonight (PST) if no one's looked at it by then.

**Comment by zackshapiro** [comment]
That’s fine. Thanks!


On Jun 22, 2018 at 5:28 PM, Dung Ta <notifications@github.com> wrote:


@zackshapiro <https://github.com/zackshapiro> I can sometime tonight (PST)
if no one's looked at it by then.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nano-wallet-company/nano-wallet-android/issues/8#issuecomment-399587389>,
or mute the thread

**Comment by dungtienta** [comment]
@slowaways Is this on the dialog that says "Copy your new Wallet Seed and transfer funds?" It looks like when you reach this dialog, you'll get a new seed generated. If you're entering anything but that seed you see on that dialog, it'll give you a "Seed does not match. Please try again" message.

The validation logic is doing a case-insensitive string comparison. If you are entering what you see on the previous dialog and it's still giving you that error, you probably copied it down incorrectly.

**Comment by rodrigoslayertech** [comment]
@dungtienta It's in dialog and I did not copy it wrong. I checked 3 times and closed it and opened the wallet again to generate a new seed thinking that I had copied it wrong, but it made a error again in the second time. Also you can not go back to check if you copied the seed correctly.

**Comment by dungtienta** [comment]
@slowaways can you shoot me a message on discord @ dungtienta#1908. I'll see if I can help you debug it.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
